import './style.css';
import { SupabaseDataService } from './supabase-service';
import type { Mode, SessionState } from './types';

const names = ['Tiger','Orcas','Kometen','Eulen','Roboter','Vulkane','Phönix','Saturn','Pinguine','Wölfe','Axolotl','Polarlichter','Drachen','Kängurus','Sternschnuppen','Nashörner','Meteore','Luchse','Korallen','Blitze'];
const app = document.querySelector<HTMLDivElement>('#app')!;
let view: 'teacher'|'student' = location.hash.startsWith('#student') ? 'student' : 'teacher';
let studentId = sessionStorage.getItem('buzzer-participant') || '';
const dataService = new SupabaseDataService();
let state: SessionState | null = dataService.getState();

function esc(s:string) { const d=document.createElement('div'); d.textContent=s; return d.innerHTML; }
function modeName(m:Mode) { return ({buzzer:'Buzzer',truefalse:'Richtig / Falsch',poll:'Umfrage',speed:'Schnelligkeit'})[m]; }
function render() { state=dataService.getState(); app.innerHTML=view==='teacher'?teacher():student(); bind(); }
function teacher() { const s=state; if(!s) return `<main class="welcome"><div class="brand">● Classroom Buzzer</div><h1>Unterricht. Sofort aktiv.</h1><p>Starte eine Sitzung, zeige den Code und los geht’s.</p><button class="primary huge" data-action="new">Neue Sitzung erstellen</button><button class="link" data-action="student">Schüleransicht testen →</button></main>`;
 const winner=s.responses[0]&&s.participants.find(p=>p.id===s.responses[0].participantId);
 const ranked=s.responses.map((r,i)=>{const p=s.participants.find(x=>x.id===r.participantId);return p?`<li><b>${i+1}</b><span class="dot" style="background:${p.color}"></span>${esc(p.name)} <em>${esc(r.value)}</em><small>${new Date(r.at).toLocaleTimeString('de-DE')}</small></li>`:''}).join('') || '<li class="empty">Noch keine Antworten</li>';
 return `<main class="dashboard"><header><div class="brand">● Classroom Buzzer</div><div><button class="quiet" data-action="student">Schüleransicht</button><button class="quiet" data-action="fullscreen">Vollbild</button></div></header><section class="hero ${winner&&s.animations?'hit':''}"><div><span class="eyebrow">Sitzungscode</span><h1>${s.code}</h1><p>${s.participants.length} Teilnehmende · ${s.active?'<strong class="live">● LIVE</strong>':'Bereit zum Start'}</p></div><div class="qr" aria-label="QR-Code"><span>▦</span><small>Code: ${s.code}</small></div><div class="hero-actions"><button class="${s.active?'danger':'primary'}" data-action="toggle">${s.active?'Sitzung stoppen':'Sitzung starten'}</button><button class="quiet" data-action="reset">Runde zurücksetzen</button></div></section><section class="grid"><aside class="panel controls"><h2>Steuerung</h2><label>Modus<select data-field="mode">${(['buzzer','truefalse','poll','speed'] as Mode[]).map(m=>`<option value="${m}" ${s.mode===m?'selected':''}>${modeName(m)}</option>`).join('')}</select></label><label class="switch"><input type="checkbox" data-field="group" ${s.groupMode?'checked':''}> Gruppenmodus</label><label class="switch"><input type="checkbox" data-field="animations" ${s.animations?'checked':''}> Animationen</label><label class="switch"><input type="checkbox" data-field="multiple" ${s.multipleWinners?'checked':''}> Mehrfachantworten</label><hr><button class="quiet" data-action="clear">Ergebnisse löschen</button><button class="quiet" data-action="newcode">Neuen Code erzeugen</button></aside><section class="panel results"><div class="panel-head"><h2>${winner?'Erste Antwort':'Live-Ergebnisse'}</h2><span>${modeName(s.mode)}</span></div>${winner?`<div class="winner" style="--winner:${winner.color}"><span>${esc(winner.name)}</span><small>${esc(s.responses[0].value)}</small></div>`:''}<ol>${ranked}</ol></section><aside class="panel"><h2>Teilnehmende</h2><div class="participants">${s.participants.map(p=>`<div><span class="dot" style="background:${p.color}"></span>${esc(p.name)}<button data-remove="${p.id}" aria-label="Entfernen">×</button></div>`).join('')||'<p class="muted">Warten auf Beitritte …</p>'}</div></aside></section></main>`; }
function student() { const s=state; if(!s) return `<main class="student-shell"><div class="brand">● Classroom Buzzer</div><section class="student-card"><h1>Sitzung beitreten</h1><p>Gib den sechsstelligen Code deiner Lehrkraft ein.</p><input id="session-code" maxlength="6" autocomplete="off" placeholder="ABC123" /><button class="primary huge" data-action="load">Sitzung öffnen</button><button class="link" data-action="teacher">Lehreransicht</button></section></main>`; const p=s.participants.find(x=>x.id===studentId); if(!p) return `<main class="student-shell"><div class="brand">● Classroom Buzzer</div><section class="student-card"><span class="eyebrow">Sitzung ${s.code}</span><h1>Willkommen!</h1><p>${s.groupMode?'Wähle einen Gruppennamen.':'Gib deine Initialen ein (max. 3 Zeichen).'}</p>${s.groupMode?`<select id="join-name">${names.map(n=>`<option>${n}</option>`).join('')}</select><button class="quiet" data-action="random">Zufällig wählen</button>`:`<input id="join-name" maxlength="3" autocomplete="off" placeholder="z. B. MS" />`}<button class="primary huge" data-action="join">Beitreten</button></section></main>`; const sent=s.responses.some(r=>r.participantId===p.id); const controls=s.mode==='truefalse'?`<button class="answer yes" data-answer="Richtig">✓<small>Richtig</small></button><button class="answer no" data-answer="Falsch">×<small>Falsch</small></button>`:s.mode==='poll'?s.pollOptions.map(x=>`<button class="answer poll" data-answer="${x}">${x}</button>`).join(''):`<button class="buzzer" data-answer="${s.mode==='speed'?'Bereit':'Buzzer'}" ${!s.active||sent?'disabled':''}><span>${sent?'Antwort gesendet':'DRÜCK MICH!'}</span></button>`; return `<main class="student-shell"><div class="student-top"><span class="dot" style="background:${p.color}"></span><b>${esc(p.name)}</b><span>${s.active?'● Live':'Warte auf Start …'}</span></div><section class="student-play"><span class="eyebrow">${modeName(s.mode)}</span><h1>${s.active?'Deine Antwort zählt.':'Gleich geht’s los.'}</h1><div class="answer-area ${s.mode}">${controls}</div></section></main>`; }
function bind(){ document.querySelectorAll<HTMLElement>('[data-action]').forEach(b=>b.onclick=()=>void act(b.dataset.action!)); document.querySelectorAll<HTMLButtonElement>('[data-answer]').forEach(b=>b.onclick=()=>void answer(b.dataset.answer!)); document.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=()=>void dataService.removeParticipantAsync(b.dataset.remove!)); document.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-field]').forEach(x=>x.onchange=()=>{if(!state)return; const k=x.dataset.field!; if(k==='mode')state.mode=x.value as Mode; else if(k==='group')state.groupMode=(x as HTMLInputElement).checked; else if(k==='animations')state.animations=(x as HTMLInputElement).checked; else state.multipleWinners=(x as HTMLInputElement).checked; dataService.saveState(state)}); }
async function act(a:string){ try { if(a==='new'||a==='newcode'){await dataService.createSessionAsync()} else if(a==='student'){view='student';location.hash=state?`student?code=${state.code}`:'student'} else if(a==='teacher'){view='teacher';history.replaceState(null,'','#teacher')} else if(a==='toggle'&&state){state.active=!state.active;dataService.saveState(state)} else if((a==='reset'||a==='clear')&&state){await dataService.clearResponsesAsync()} else if(a==='fullscreen')document.documentElement.requestFullscreen?.(); else if(a==='load'){const code=(document.querySelector<HTMLInputElement>('#session-code')?.value||'').trim();if(code){await dataService.loadByCode(code);if(!dataService.getState())alert('Sitzung nicht gefunden.')}} else if(a==='join'){const n=(document.querySelector<HTMLInputElement|HTMLSelectElement>('#join-name')?.value||'').trim().toUpperCase();if(n){studentId=(await dataService.joinSessionAsync(n)).id;sessionStorage.setItem('buzzer-participant',studentId)}} else if(a==='random'){const el=document.querySelector<HTMLSelectElement>('#join-name');if(el)el.value=names[Math.floor(Math.random()*names.length)]} render(); } catch(error) { alert(error instanceof Error ? error.message : 'Verbindung zu Supabase fehlgeschlagen.'); } }
async function answer(value:string){if(!studentId)return; navigator.vibrate?.(35); try { await dataService.submitBuzzAsync(studentId,value); } catch(error) { alert(error instanceof Error ? error.message : 'Antwort konnte nicht gesendet werden.'); } render();}
window.addEventListener('buzzer-state',render); if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js'); const code=new URLSearchParams(location.hash.split('?')[1]||'').get('code'); if(view==='student'&&code) void dataService.loadByCode(code).catch(()=>undefined); render();
